// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Device = __t.object("Device", {
  deviceId: __t.string(),
  ownerIdentity: __t.identity(),
  lastSyncTime: __t.timestamp(),
});
export type Device = __Infer<typeof Device>;

export const Document = __t.object("Document", {
  path: __t.string(),
  content: __t.string(),
  contentBytes: __t.byteArray(),
  lastModified: __t.timestamp(),
});
export type Document = __Infer<typeof Document>;

